examples:
  security:
    api:
      username: api
      password: AP19rs#$

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
